// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmho_UX6ipM8sC3NV3z7gg4IaixNnIg30',
    appId: '1:949233826127:web:78f863e8fc091853876d3a',
    messagingSenderId: '949233826127',
    projectId: 'ttestechat-e1928',
    authDomain: 'ttestechat-e1928.firebaseapp.com',
    storageBucket: 'ttestechat-e1928.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWIv4dP5Ks8McuTwpd7Fx3ted5F8eE1O8',
    appId: '1:949233826127:android:2ce58c0332055fed876d3a',
    messagingSenderId: '949233826127',
    projectId: 'ttestechat-e1928',
    storageBucket: 'ttestechat-e1928.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZwO6q41rWO-QA6h_Ww9xXYO36eZBHYY',
    appId: '1:949233826127:ios:e070162603a24b99876d3a',
    messagingSenderId: '949233826127',
    projectId: 'ttestechat-e1928',
    storageBucket: 'ttestechat-e1928.firebasestorage.app',
    iosBundleId: 'com.example.novoprojchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPZwO6q41rWO-QA6h_Ww9xXYO36eZBHYY',
    appId: '1:949233826127:ios:e070162603a24b99876d3a',
    messagingSenderId: '949233826127',
    projectId: 'ttestechat-e1928',
    storageBucket: 'ttestechat-e1928.firebasestorage.app',
    iosBundleId: 'com.example.novoprojchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmho_UX6ipM8sC3NV3z7gg4IaixNnIg30',
    appId: '1:949233826127:web:99588f0fdf832b27876d3a',
    messagingSenderId: '949233826127',
    projectId: 'ttestechat-e1928',
    authDomain: 'ttestechat-e1928.firebaseapp.com',
    storageBucket: 'ttestechat-e1928.firebasestorage.app',
  );
}
